# Libraries

In [2]:
import pandas as pd 
from bs4 import BeautifulSoup
import requests
import numpy as np
from time import sleep
from random import randint
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import re

# Reading CSV and cleaning Data

In [3]:
data2021 = pd.read_csv('DF_data20202021.csv')
data1920 = pd.read_csv('DF_data20192020.csv')
data1819 = pd.read_csv('DF_data20182019.csv')
data1718 = pd.read_csv('DF_data20172018.csv')

In [4]:
datapage7 = pd.read_csv('DF_datapage7.csv')

In [5]:
data1718.rename(columns = {'0':'Links','0.1':'Date','0.2':'Home team','0.3':'Away team'}, inplace = True)
data1718.drop(['Unnamed: 0'], axis=1,inplace=True)

In [6]:
data1819.rename(columns = {'0':'Links','0.1':'Date','0.2':'Home team','0.3':'Away team'}, inplace = True)
data1819.drop(['Unnamed: 0'], axis=1,inplace=True)
data1819

,Links,Date,Home team,Away team
0,https://www.zerozero.pt/jogo.php?id=6067456,2018-08-10,Benfica,V. Guimarães
1,https://www.zerozero.pt/jogo.php?id=6067460,2018-08-11,V. Setúbal,CD Aves
2,https://www.zerozero.pt/jogo.php?id=6067461,2018-08-11,CD Tondela,Belenenses SAD
3,https://www.zerozero.pt/jogo.php?id=6067463,2018-08-11,FC Porto,GD Chaves
4,https://www.zerozero.pt/jogo.php?id=6067464,2018-08-12,Marítimo,Santa Clara
...,...,...,...,...
295,https://www.zerozero.pt/jogo.php?id=6067751,2019-05-12,Nacional,FC Porto
296,https://www.zerozero.pt/jogo.php?id=6067745,2019-05-12,Rio Ave,Benfica
297,https://www.zerozero.pt/jogo.php?id=6067758,2019-05-16,Belenenses SAD,Nacional
298,https://www.zerozero.pt/jogo.php?id=6067760,2019-05-17,SC Braga,Portimonense
299,https://www.zerozero.pt/jogo.php?id=6067754,2019-05-18,Marítimo,Boavista

In [7]:
data1920.rename(columns = {'0':'Links','0.1':'Date','0.2':'Home team','0.3':'Away team'}, inplace = True)
data1920.drop(['Unnamed: 0'], axis=1,inplace=True)
data1920

,Links,Date,Home team,Away team
0,https://www.zerozero.pt/jogo.php?id=6958518,2019-08-09,Portimonense,Belenenses SAD
1,https://www.zerozero.pt/jogo.php?id=6958515,2019-08-10,Santa Clara,FC Famalicão
2,https://www.zerozero.pt/jogo.php?id=6958511,2019-08-10,Gil Vicente,FC Porto
3,https://www.zerozero.pt/jogo.php?id=6958516,2019-08-10,Benfica,Paços de Ferreira
4,https://www.zerozero.pt/jogo.php?id=6958517,2019-08-11,Boavista,CD Aves
...,...,...,...,...
295,https://www.zerozero.pt/jogo.php?id=6958803,2020-07-21,Sporting,V. Setúbal
296,https://www.zerozero.pt/jogo.php?id=6958806,2020-07-21,CD Aves,Benfica
297,https://www.zerozero.pt/jogo.php?id=6958815,2020-07-24,Santa Clara,V. Guimarães
298,https://www.zerozero.pt/jogo.php?id=6958811,2020-07-24,Gil Vicente,Paços de Ferreira
299,https://www.zerozero.pt/jogo.php?id=6958813,2020-07-25,Boavista,Rio Ave

In [8]:
data2021.rename(columns = {'0':'Links','0.1':'Date','0.2':'Home team','0.3':'Away team'}, inplace = True)
data2021.drop(['Unnamed: 0'], axis=1,inplace=True)
data2021

,Links,Date,Home team,Away team
0,https://www.zerozero.pt/jogo.php?id=7642938,2020-09-18,FC Famalicão,Benfica
1,https://www.zerozero.pt/jogo.php?id=7642944,2020-09-18,V. Guimarães,Belenenses SAD
2,https://www.zerozero.pt/jogo.php?id=7642940,2020-09-19,Nacional,Boavista
3,https://www.zerozero.pt/jogo.php?id=7642948,2020-09-19,FC Porto,SC Braga
4,https://www.zerozero.pt/jogo.php?id=7642942,2020-09-20,Santa Clara,Marítimo
...,...,...,...,...
295,https://www.zerozero.pt/jogo.php?id=7642993,2021-05-16,Paços de Ferreira,Gil Vicente
296,https://www.zerozero.pt/jogo.php?id=7642997,2021-05-16,Belenenses SAD,Santa Clara
297,https://www.zerozero.pt/jogo.php?id=7643059,2021-05-19,Sporting,Marítimo
298,https://www.zerozero.pt/jogo.php?id=7643061,2021-05-19,Santa Clara,Farense
299,https://www.zerozero.pt/jogo.php?id=7643063,2021-05-19,Nacional,Rio Ave

In [9]:
datapage7.rename(columns = {'0':'Links','0.1':'Date','0.2':'Home team','0.3':'Away team'}, inplace = True)
datapage7.drop(['Unnamed: 0'], axis=1,inplace=True)
datapage7

,Links,Date,Home team,Away team
0,https://www.zerozero.pt/jogo.php?id=5442767,2018-05-13,V. Setúbal,CD Tondela
1,https://www.zerozero.pt/jogo.php?id=5442766,2018-05-13,Marítimo,Sporting
2,https://www.zerozero.pt/jogo.php?id=5442761,2018-05-13,Feirense,Estoril Praia
3,https://www.zerozero.pt/jogo.php?id=5442760,2018-05-13,Rio Ave,SC Braga
4,https://www.zerozero.pt/jogo.php?id=5442762,2018-05-13,Portimonense,Paços de Ferreira
5,https://www.zerozero.pt/jogo.php?id=5442764,2018-05-13,Benfica,Moreirense
6,https://www.zerozero.pt/jogo.php?id=6067757,2019-05-18,V. Setúbal,Rio Ave
7,https://www.zerozero.pt/jogo.php?id=6067753,2019-05-18,Feirense,CD Aves
8,https://www.zerozero.pt/jogo.php?id=6067759,2019-05-18,Benfica,Santa Clara
9,https://www.zerozero.pt/jogo.php?id=6067761,2019-05-18,FC Porto,Sporting
10,https://www.zerozero.pt/jogo.php?id=6067755,2019-05-19,CD Tondela,GD Chaves
11,https://www.zerozero.pt/jogo.php?id=6067756,2019-05-19,Moreirense,V. Guimarães
12,https://www.zerozero.pt/jogo.php?id=6958808,2020-07-25,Marítimo,FC Famalicão
13,https://www.zerozero.pt/jogo.php?id=6958814,2020-07-25,SC Braga,FC Porto
14,https://www.zerozero.pt/jogo.php?id=6958812,2020-07-25,Benfica,Sporting
15,https://www.zerozero.pt/jogo.php?id=6958816,2020-07-26,Moreirense,CD Tondela
16,https://www.zerozero.pt/jogo.php?id=6958810,2020-07-26,V. Setúbal,Belenenses SAD
17,https://www.zerozero.pt/jogo.php?id=6958809,2020-07-26,Portimonense,CD Aves

In [10]:
DF_data = pd.concat([data1718,data1819,data1920,data2021], axis=0)
DF_data.reset_index(inplace=True)
DF_data.drop(['index'], axis=1,inplace=True)

In [11]:
DF_data

,Links,Date,Home team,Away team
0,https://www.zerozero.pt/jogo.php?id=5442462,2017-08-06,CD Aves,Sporting
1,https://www.zerozero.pt/jogo.php?id=5442470,2017-08-06,V. Setúbal,Moreirense
2,https://www.zerozero.pt/jogo.php?id=5442466,2017-08-07,Portimonense,Boavista
3,https://www.zerozero.pt/jogo.php?id=5442464,2017-08-07,Feirense,CD Tondela
4,https://www.zerozero.pt/jogo.php?id=5442465,2017-08-07,Rio Ave,Belenenses
...,...,...,...,...
1195,https://www.zerozero.pt/jogo.php?id=7642993,2021-05-16,Paços de Ferreira,Gil Vicente
1196,https://www.zerozero.pt/jogo.php?id=7642997,2021-05-16,Belenenses SAD,Santa Clara
1197,https://www.zerozero.pt/jogo.php?id=7643059,2021-05-19,Sporting,Marítimo
1198,https://www.zerozero.pt/jogo.php?id=7643061,2021-05-19,Santa Clara,Farense
1199,https://www.zerozero.pt/jogo.php?id=7643063,2021-05-19,Nacional,Rio Ave

In [12]:
#https://www.zerozero.pt/jogo.php?id=7643087
DF_data[DF_data.eq('https://www.zerozero.pt/jogo.php?id=7643087').any(1)]

,Links,Date,Home team,Away team
1088,https://www.zerozero.pt/jogo.php?id=7643087,2021-03-01,Moreirense,Belenenses SAD

In [13]:
DF_data.drop(DF_data.index[1089:],inplace=True)

In [14]:
DF_data = pd.concat([DF_data,datapage7], axis=0)
DF_data.reset_index(inplace=True)
DF_data.drop(['index'], axis=1,inplace=True)

In [15]:
DF_data

,Links,Date,Home team,Away team
0,https://www.zerozero.pt/jogo.php?id=5442462,2017-08-06,CD Aves,Sporting
1,https://www.zerozero.pt/jogo.php?id=5442470,2017-08-06,V. Setúbal,Moreirense
2,https://www.zerozero.pt/jogo.php?id=5442466,2017-08-07,Portimonense,Boavista
3,https://www.zerozero.pt/jogo.php?id=5442464,2017-08-07,Feirense,CD Tondela
4,https://www.zerozero.pt/jogo.php?id=5442465,2017-08-07,Rio Ave,Belenenses
...,...,...,...,...
1102,https://www.zerozero.pt/jogo.php?id=6958814,2020-07-25,SC Braga,FC Porto
1103,https://www.zerozero.pt/jogo.php?id=6958812,2020-07-25,Benfica,Sporting
1104,https://www.zerozero.pt/jogo.php?id=6958816,2020-07-26,Moreirense,CD Tondela
1105,https://www.zerozero.pt/jogo.php?id=6958810,2020-07-26,V. Setúbal,Belenenses SAD
1106,https://www.zerozero.pt/jogo.php?id=6958809,2020-07-26,Portimonense,CD Aves

In [16]:
DF_data.to_excel('data_links.xlsx')

# Getting Data

In [26]:
games_links = DF_data['Links'].tolist()

In [ ]:
response = requests.get('https://www.zerozero.pt/jogo.php?id=7642938')
players_soup = BeautifulSoup(response.content)

In [ ]:
player_active_box = players_soup.find_all('div', attrs={'class':'section_620 game_report'})[0]
player_sup_box = players_soup.find_all('div', attrs={'class':'section_620 game_report'})[1]

In [ ]:
# starts
home_team_active = player_active_box.find_all('div', attrs={'class': 'column_300'})[0]
away_team_active = player_active_box.find_all('div', attrs={'class': 'column_300'})[1]
# bench 
home_team_sup = player_sup_box.find_all('div', attrs={'class': 'column_300'})[0]
away_team_sup =player_sup_box.find_all('div', attrs={'class': 'column_300'})[1]

In [ ]:
# starts
home_lis = [player.text for player in home_team_active.find_all('div', attrs={'class': 'text'})]
display(home_lis)
# bench 
home_sup = [player.text for player in home_team_sup.find_all('div', attrs={'class': 'text'})]
display(home_sup)

print('\n')

# starts
away_lis = [player.text for player in away_team_active.find_all('div', attrs={'class': 'text'})]
display(away_lis)

# bench 
away_sup = [player.text for player in away_team_sup.find_all('div', attrs={'class': 'text'})]
display(away_sup)

In [ ]:
#20202021
#Loop to go over all pages
pages = np.arange(1, 7, 1)
data=[]


for page in pages:
    
    page="https://www.zerozero.pt/edition_matches.php?id_edicao=147383&page=" + str(page) 
    driver = webdriver.Chrome()
    driver.get(page)
    link = driver.find_element_by_link_text('aqui')
    link.click()
    sleep(randint(2,5))
    html = driver.page_source
    sleep(randint(2,5))
    data.append(html)

# home players

In [360]:
# HOME & AWAY PLAYERS
#going for 419 KEEP GOING TOMAS
homeplayers_48=[]
awayplayers_48=[]

for link in DF_data['Links'][1102:].values:
    #main engine
    print(link)
    sleep(3)
    response = requests.get(link)
    sleep(3)
    players_soup = BeautifulSoup(response.content)

    # getting to the starting 11
    player_active_box = players_soup.find_all('div', attrs={'class':'section_620 game_report'})[0]
    sleep(3)
    
    # getting home players
    home_team_active = player_active_box.find_all('div', attrs={'class': 'column_300'})[0]
    sleep(3)
    home_lis = [player.text for player in home_team_active.find_all('div', attrs={'class': 'text'})]
    sleep(3)
    homeplayers_48.append(home_lis)
    
    
    #getting away players
    away_team_active = player_active_box.find_all('div', attrs={'class': 'column_300'})[1]
    sleep(3)
    away_lis = [player.text for player in away_team_active.find_all('div', attrs={'class': 'text'})]
    sleep(3)
    awayplayers_48.append(away_lis)

https://www.zerozero.pt/jogo.php?id=6958814
https://www.zerozero.pt/jogo.php?id=6958812
https://www.zerozero.pt/jogo.php?id=6958816
https://www.zerozero.pt/jogo.php?id=6958810
https://www.zerozero.pt/jogo.php?id=6958809

In [361]:
#links we have
homeplayers #17
awayplayers #17
homeplayers_1 #17
awayplayers_1 #17
homeplayers_2 #36
awayplayers_2 #36
homeplayers_3 #17
awayplayers_3 #17
homeplayers_4 #33
awayplayers_4 #33
homeplayers_5 #33
awayplayers_5 #33
homeplayers_6 #17
awayplayers_6 #17
homeplayers_7 #17
awayplayers_7 #17
homeplayers_8 #17
awayplayers_8 #17
homeplayers_9 #17
awayplayers_9 #17
homeplayers_10 #25
awayplayers_10 #25
homeplayers_11 #28
awayplayers_11 #28
homeplayers_12 #17
awayplayers_12 #17
homeplayers_13 #21
awayplayers_13 #21
homeplayers_14 #22
awayplayers_14 #22
homeplayers_15 #34
awayplayers_15 #34
homeplayers_16 #34
awayplayers_16 #34
homeplayers_17 #17
awayplayers_17 #17
homeplayers_18 #17
awayplayers_18 #17
homeplayers_19 #17
awayplayers_19 #17
homeplayers_20 #17
awayplayers_20 #17
homeplayers_21 #17
awayplayers_21 #17
homeplayers_22 #22
awayplayers_22 #22
homeplayers_23 #16
awayplayers_23 #16
homeplayers_24 #17
awayplayers_24 #17
homeplayers_25 #17
awayplayers_25 #17
homeplayers_26 #18
awayplayers_26 #18
homeplayers_27 #17
awayplayers_27 #17
homeplayers_28 #31
awayplayers_28 #31
homeplayers_29 #34
awayplayers_29 #34
homeplayers_30 #33
awayplayers_30 #33
homeplayers_31 #29
awayplayers_31 #29
homeplayers_32 #33
awayplayers_32 #33
homeplayers_33 #34
awayplayers_33 #34
homeplayers_34 #32
awayplayers_34 #32
homeplayers_35 #33
awayplayers_35 #33
homeplayers_36 #28
awayplayers_36 #28
homeplayers_37 #31
awayplayers_37 #31
homeplayers_38 #17
awayplayers_38 #17
homeplayers_39 #17
awayplayers_39 #17
homeplayers_40 #17
awayplayers_40 #17
homeplayers_41 #30
awayplayers_41 #30
homeplayers_42 #17
awayplayers_42 #17
homeplayers_43 #17
awayplayers_43 #17
homeplayers_44 #29
awayplayers_44 #29
homeplayers_45 #17
awayplayers_45 #17
homeplayers_46 #16
awayplayers_46 #16
homeplayers_47 #13
awayplayers_47 #13
homeplayers_48 #
awayplayers_48 #
#see which links we have
print(len(homeplayers_48))
print(len(awayplayers_48))
list_homeplayers = homeplayers + homeplayers_1 + homeplayers_2 + homeplayers_3 + homeplayers_4 + homeplayers_5 + homeplayers_6+ homeplayers_7 + homeplayers_8+ homeplayers_9+ homeplayers_10+ homeplayers_11+ homeplayers_12+ homeplayers_13+ homeplayers_14+ homeplayers_15+ homeplayers_16+ homeplayers_17+ homeplayers_18+ homeplayers_19+ homeplayers_20+ homeplayers_21+ homeplayers_22+ homeplayers_23+ homeplayers_24+ homeplayers_25+ homeplayers_26+ homeplayers_27+ homeplayers_28+ homeplayers_29+ homeplayers_30+ homeplayers_31+ homeplayers_32+ homeplayers_33+ homeplayers_34+ homeplayers_35+ homeplayers_36+ homeplayers_37+ homeplayers_38+ homeplayers_39+ homeplayers_40+ homeplayers_41+ homeplayers_42+ homeplayers_43+ homeplayers_44+ homeplayers_45+ homeplayers_46+ homeplayers_47+ homeplayers_48
list_awayplayers = awayplayers + awayplayers_1 + awayplayers_2 + awayplayers_3 + awayplayers_4 + awayplayers_5 + awayplayers_6+ awayplayers_7 + awayplayers_8+ awayplayers_9+ awayplayers_10+ awayplayers_11+ awayplayers_12+ awayplayers_13+ awayplayers_14+ awayplayers_15+ awayplayers_16+ awayplayers_17+ awayplayers_18+ awayplayers_19+ awayplayers_20+ awayplayers_21+ awayplayers_22+ awayplayers_23+ awayplayers_24+ awayplayers_25+ awayplayers_26+ awayplayers_27+ awayplayers_28+ awayplayers_29+ awayplayers_30+ awayplayers_31+ awayplayers_32+ awayplayers_33+ awayplayers_34+ awayplayers_35+ awayplayers_36+ awayplayers_37+ awayplayers_38+ awayplayers_39+ awayplayers_40+ awayplayers_41+ awayplayers_42+ awayplayers_43+ awayplayers_44+ awayplayers_45+ awayplayers_46+ awayplayers_47+ awayplayers_48
#print(list_homeplayers)

5
5

In [362]:
homeplayers_final=[]
awayplayers_final=[]

for player in list_homeplayers:
    a = pd.DataFrame(data=player).set_index(0).T
    a.loc[len(a)] = 1    
    homeplayers_final.append(a)
    
for player in list_awayplayers:
    b = pd.DataFrame(data=player).set_index(0).T
    b.loc[len(b)] = 1    
    awayplayers_final.append(b)
    
display(pd.concat(homeplayers_final))
display(pd.concat(awayplayers_final))

,Adriano Facchini,Rodrigo Soares,Carlos Ponck,Diego Galo,Nélson Lenho (C),Washington,Cláudio Falcão,Braga,Salvador Agra,Alexandre Guedes,...,Abdoulaye Ba,Gonçalo Inácio,Roberto Olabe,Nélson Monte (C),Sávio Alves,Lucas Veríssimo,Luisão (C),Eduardo Salvio,Nuno Pinto (C),Allef
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Rui Patrício,Cristiano Piccini,Sebastián Coates,Jérémy Mathieu,Fábio Coentrão,William Carvalho,Bruno Fernandes,Adrien Silva (C),Gelson Martins,Bas Dost,...,Bruno Rodrigues,Sávio Alves,Matheus Sávio,Paulo Vítor,Ricardo Rodrigues,Roderick Miranda (C),Marcos Acuña (C),Dimitar Sheytanov,Cláudio Tavares,Mohamed Touré
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0

In [364]:
homeplayers_final = pd.concat(homeplayers_final)
homeplayers_final.reset_index(inplace=True)
homeplayers_final.drop(['index'], axis=1,inplace=True)
homeplayers_final

,Adriano Facchini,Rodrigo Soares,Carlos Ponck,Diego Galo,Nélson Lenho (C),Washington,Cláudio Falcão,Braga,Salvador Agra,Alexandre Guedes,...,Abdoulaye Ba,Gonçalo Inácio,Roberto Olabe,Nélson Monte (C),Sávio Alves,Lucas Veríssimo,Luisão (C),Eduardo Salvio,Nuno Pinto (C),Allef
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [365]:
awayplayers_final = pd.concat(awayplayers_final)
awayplayers_final.reset_index(inplace=True)
awayplayers_final.drop(['index'], axis=1,inplace=True)
awayplayers_final

,Rui Patrício,Cristiano Piccini,Sebastián Coates,Jérémy Mathieu,Fábio Coentrão,William Carvalho,Bruno Fernandes,Adrien Silva (C),Gelson Martins,Bas Dost,...,Bruno Rodrigues,Sávio Alves,Matheus Sávio,Paulo Vítor,Ricardo Rodrigues,Roderick Miranda (C),Marcos Acuña (C),Dimitar Sheytanov,Cláudio Tavares,Mohamed Touré
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0

In [437]:
homeplayers_final.fillna(0).to_excel('homeplayers_final.xlsx')
awayplayers_final.fillna(0).to_excel('awayplayers_final.xlsx')

# game stats

In [162]:
url = 'https://www.zerozero.pt/jogo.php?id=7642938'

response = requests.get(url)
response

In [163]:
soup = BeautifulSoup(response.content)

In [164]:
# get stats right bar 

stats_object = soup.find_all('div', attrs= {'class' : 'rbbox nofooter'})[0]

In [165]:
# entering in the object 

stats_total = stats_object.find('div', attrs= {'class' : 'rbbox'})

In [168]:
stats = stats_total.find_all('div')
stats

li = []

for s in stats:
    if s.get('title') != None:
        li.append(s.get('title'))
print(len(li))
li=li[::2]

68

In [131]:
numbers=[]

for string in li:
    a = int(re.search(r'\d+', string).group())
    numbers.append(a)

print(numbers)

[1, 1, 210, 428, 12, 8, 3, 1, 2, 7, 6, 14, 20, 36, 9, 3, 309, 500, 10, 15, 23, 16, 1, 2, 3, 6, 15, 10, 3, 4, 38, 62, 22, 9]

In [133]:
#creates a dataframe with all the stats
a=pd.DataFrame(data=numbers)

#gets the away team stats
away_team_stats = a.iloc[1::2, :].T

#gets the home team stats
home_team_stats = a.iloc[0::2, :].T

display(away_team_stats)
display(home_team_stats)

   1    3   5   7   9   11  13  15   17  19  21  23  25  27  29  31  33
0   1  428   8   1   7  14  36   3  500  15  16   2   6  10   4  62   9

   0    2   4   6   8   10  12  14   16  18  20  22  24  26  28  30  32
0   1  210  12   3   2   6  20   9  309  10  23   1   3  15   3  38  22

# joining 3 game stats

In [351]:
li_4=[]

for link in DF_data['Links'][68:].values:
    print(link)
 
    response = requests.get(link)
    sleep(2)
    stats_soup = BeautifulSoup(response.content)

    stats_object = stats_soup.find_all('div', attrs= {'class' : 'rbbox nofooter'})[0]
    sleep(2)
    
    e=[]
    try:
        stats_total = stats_object.find('div', attrs= {'class' : 'rbbox'})
        sleep(2)
        stats = stats_total.find_all('div')
        sleep(2)
        
        for s in stats:
            if s.get('title') != None:
                e.append(s.get('title'))
                sleep(2)
                
            numbers=[]
            for string in e:
                a = int(re.search(r'\d+', string).group())
                numbers.append(a)
                
        li_4.append(numbers[::2])
    except:
        li_4.append([0]*12)
        print('error')

https://www.zerozero.pt/jogo.php?id=5442527
error
https://www.zerozero.pt/jogo.php?id=5442533
error
https://www.zerozero.pt/jogo.php?id=5442532
error
https://www.zerozero.pt/jogo.php?id=5442525
error
https://www.zerozero.pt/jogo.php?id=5442538
error
https://www.zerozero.pt/jogo.php?id=5442535
error
https://www.zerozero.pt/jogo.php?id=5442542
error
https://www.zerozero.pt/jogo.php?id=5442541
error
https://www.zerozero.pt/jogo.php?id=5442537
error
https://www.zerozero.pt/jogo.php?id=5442534
error
https://www.zerozero.pt/jogo.php?id=5442540
error
https://www.zerozero.pt/jogo.php?id=5442539
error
https://www.zerozero.pt/jogo.php?id=5442536
error
https://www.zerozero.pt/jogo.php?id=5442545
error
https://www.zerozero.pt/jogo.php?id=5442550
error
https://www.zerozero.pt/jogo.php?id=5442548
error
https://www.zerozero.pt/jogo.php?id=5442544
error
https://www.zerozero.pt/jogo.php?id=5442546

IndexError: list index out of range

In [350]:
li #17
li_1 #17
li_2 #17
li_3 #17
li_4 #
print(len(li_4))
stats_list= li + li_1+ li_2+ li_3+ li_4+ li_5+ li_6+ li_7+ li_8+ li_9+ li_10+ li_11+ li_12+ li_13+ li_14+ li_15+ li_16+ li_17+ li_18

17

In [435]:
#pd.DataFrame(stats_list)

# game stats through dataset

In [423]:
gamestats1718 = pd.read_csv('P1-1718.csv')
gamestats1819 = pd.read_csv('P1-1819.csv')
gamestats1920 = pd.read_csv('P1-1920.csv')
gamestats2021 = pd.read_csv('P1-2021.csv')

In [424]:
gamestats1718 = gamestats1718.loc[:, :'AR']
gamestats1819 = gamestats1819.loc[:, :'AR']
gamestats1920 = gamestats1920.loc[:, :'AR']
gamestats2021 = gamestats2021.loc[:, :'AR']

In [425]:
gamestats1718 = gamestats1718.drop(['Div', 'FTR', 'HTR'], axis=1)
gamestats1819 = gamestats1819.drop(['Div', 'FTR', 'HTR'], axis=1)
gamestats1920 = gamestats1920.drop(['Div', 'Time', 'FTR', 'HTR'], axis=1)
gamestats2021 = gamestats2021.drop(['Div', 'Time', 'FTR', 'HTR'], axis=1)

In [427]:
gamestats1718_tail = gamestats1718[300:]
gamestats1819_tail = gamestats1819[300:]
gamestats1920_tail = gamestats1920[300:]

In [428]:
gamestats1718_head = gamestats1718[:300]
gamestats1819_head = gamestats1819[:300]
gamestats1920_head = gamestats1920[:300]

In [429]:
DF_gamestats = pd.concat([gamestats1718_head,gamestats1819_head,gamestats1920_head,gamestats2021,gamestats1718_tail,gamestats1819_tail,gamestats1920_tail], axis=0)
DF_gamestats.reset_index(inplace=True)
DF_gamestats.drop(['index'], axis=1,inplace=True)
DF_gamestats

,Date,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,06/08/17,Aves,Sp Lisbon,0,2,0,1,12,12,2,9,15,16,6,3,1,0,0,0
1,06/08/17,Setubal,Moreirense,1,1,1,0,6,12,2,4,18,22,4,8,1,3,1,0
2,07/08/17,Feirense,Tondela,1,1,0,1,12,13,5,6,19,25,5,3,4,1,0,0
3,07/08/17,Portimonense,Boavista,2,1,0,1,12,5,4,2,14,10,9,4,1,1,0,0
4,07/08/17,Rio Ave,Belenenses,1,0,1,0,11,10,5,3,17,23,4,8,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1102,25/07/2020,Benfica,Sp Lisbon,2,1,1,0,17,12,4,5,21,14,8,3,4,3,0,0
1103,25/07/2020,Sp Braga,Porto,2,1,0,1,11,10,5,5,16,13,8,3,6,3,0,0
1104,26/07/2020,Moreirense,Tondela,1,2,0,1,10,14,5,6,19,18,5,4,3,2,0,0
1105,26/07/2020,Portimonense,Aves,2,0,0,0,13,10,5,3,19,20,6,4,2,3,0,0
1106,26/07/2020,Setubal,Belenenses,2,0,1,0,11,8,4,2,15,9,2,4,3,1,0,0

In [430]:
DF_gamestats.rename(columns = {'FTHG':'Full Time Home Team Goals','FTAG':'Full Time Away Team Goals','HTHG':'Half Time Home Team Goals','HTAG':'Half Time Away Team Goals','HS':'Home Team Shots','AS':'Away Team Shots','HST':'Home Team Shots on Target','AST':'Away Team Shots on Target','HHW':'Home Team Hit Woodwork','AHW':'Away Team Hit Woodwork','HC':'Home Team Corners','AC':'Away Team Corners','HF':'Home Team Fouls Committed','AF':'Away Team Fouls Committed','HFKC':'Home Team Free Kicks Conceded','AFKC':'Away Team Free Kicks Conceded','HO':'Home Team Offsides','AO':'Away Team Offsides','HY':'Home Team Yellow Cards','AY':'Away Team Yellow Cards','HR':'Home Team Red Cards','AR':'Away Team Red Cards'}, inplace = True)

In [431]:
DF_gamestats.drop(['HomeTeam','AwayTeam'], axis=1,inplace=True)

In [433]:
#gets the away team stats
away_team_stats = DF_gamestats[['Full Time Away Team Goals','Half Time Away Team Goals','Away Team Shots','Away Team Shots on Target','Away Team Fouls Committed','Away Team Corners','Away Team Yellow Cards','Away Team Red Cards','Date']]

#gets the home team stats
home_team_stats = DF_gamestats[['Full Time Home Team Goals','Half Time Home Team Goals','Home Team Shots','Home Team Shots on Target','Home Team Fouls Committed','Home Team Corners','Home Team Yellow Cards','Home Team Red Cards','Date']]

display(away_team_stats)
display(home_team_stats)

,Full Time Away Team Goals,Half Time Away Team Goals,Away Team Shots,Away Team Shots on Target,Away Team Fouls Committed,Away Team Corners,Away Team Yellow Cards,Away Team Red Cards,Date
0,2,1,12,9,16,3,0,0,06/08/17
1,1,0,12,4,22,8,3,0,06/08/17
2,1,1,13,6,25,3,1,0,07/08/17
3,1,1,5,2,10,4,1,0,07/08/17
4,0,0,10,3,23,8,2,0,07/08/17
...,...,...,...,...,...,...,...,...,...
1102,1,0,12,5,14,3,3,0,25/07/2020
1103,1,1,10,5,13,3,3,0,25/07/2020
1104,2,1,14,6,18,4,2,0,26/07/2020
1105,0,0,10,3,20,4,3,0,26/07/2020
1106,0,0,8,2,9,4,1,0,26/07/2020

,Full Time Home Team Goals,Half Time Home Team Goals,Home Team Shots,Home Team Shots on Target,Home Team Fouls Committed,Home Team Corners,Home Team Yellow Cards,Home Team Red Cards,Date
0,0,0,12,2,15,6,1,0,06/08/17
1,1,1,6,2,18,4,1,1,06/08/17
2,1,0,12,5,19,5,4,0,07/08/17
3,2,0,12,4,14,9,1,0,07/08/17
4,1,1,11,5,17,4,2,0,07/08/17
...,...,...,...,...,...,...,...,...,...
1102,2,1,17,4,21,8,4,0,25/07/2020
1103,2,0,11,5,16,8,6,0,25/07/2020
1104,1,0,10,5,19,5,3,0,26/07/2020
1105,2,0,13,5,19,6,2,0,26/07/2020
1106,2,1,11,4,15,2,3,0,26/07/2020

In [434]:
home_team_stats.to_excel('home_team_stats.xlsx')
away_team_stats.to_excel('away_team_stats.xlsx')